# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: simplifyqa-pipeline-executor-v2@2
  inputs:
    PIPELINEID: 23
    APIKEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL2FwcC5zaW1wbGlmeXFhLmFpIiwiY3VzdG9tZXJJZCI6MiwiY29tcGFueU5hbWUiOiJQcmVwcm9kIiwibGljZW5zZV90eXBlIjpbIndlYiIsImFuZHJvaWQiLCJpb3MiLCJhcGkiLCJkYiJdLCJpbnN0YWxsZXJVcmwiOiJodHRwczovL2FwcC5zaW1wbGlmeXFhLmFpL2luc3RhbGxlci1zZXJ2aWNlIiwidXNlcklkIjozLCJpYXQiOjE3NDM2ODY3MTcsImV4cCI6MTc3NTI0NDMxN30.s8Y3woyF25WvgrTDdTWLuE9_PyNkP_rvS9vi2BltBgU'
    APIURL: 'https://app.simplifyqa.ai/'
    THRESHOLD: 50
    VERBOSE: true
